project_name: apex
builds:
  - id: darwin-amd64
    main: ./cmd/apex
    binary: apex
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: darwin-arm64
    main: ./cmd/apex
    binary: apex
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: windows-amd64
    main: ./cmd/apex
    binary: apex
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: linux-amd64
    main: ./cmd/apex
    binary: apex
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  # - id: linux-arm64
  #   main: ./cmd/apex
  #   binary: apex
  #   goos:
  #     - linux
  #   goarch:
  #     - arm64
  #   env:
  #     - CC=aarch64-linux-gnu-gcc
  #     - CXX=aarch64-linux-gnu-g++
  #   flags:
  #     - -mod=readonly
  #   ldflags:
  #     - -s -w -X main.version={{.Version}}
archives:
  - id: apex
    builds:
      - darwin-amd64
      - darwin-arm64
      - windows-amd64
      - linux-amd64
      # - linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
        - README.md
        - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: Apex
    tap:
      owner: apexlang
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/apexlang/cli
    description: A top-down / API-first description language for modeling and generating cloud-native applications
    license: "Apache-2.0"

release:
  github:
    owner: apexlang
    name: cli
  prerelease: auto
  draft: false